tenta assim




services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      DEBUG: 1
      SECRET_KEY: mysecretkey
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASSWORD: password
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,ec2-54-233-224-70.sa-east-1.compute.amazonaws.com
    depends_on:
      - db

  db:
    image: postgres:14
    networks:
      - app-network
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network: