services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
     sh -c "python manage.py wait_for_db &&
          python manage.py migrate &&
          python manage.py runserver 0.0.0:8000"
    
    networks:
      - app-network 
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment: 
      - DEBUG=1
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db

  db: 
    image: postgres:14
    networks:
      - app-network
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

networks:
  app-network:
